const cartas = [
  {
    "id": 1,
    "nome": "Elminster",
    "raridade": "lendaria",
    "pontos": 10,
    "forca": 20,
    "destreza": 16,
    "magia": 18,
    "velocidade": 16,
    "inteligencia": 18,
    "resistencia": "velocidade"
  },
  {
    "id": 2,
    "nome": "Drizzt Do'Urden",
    "raridade": "lendaria",
    "pontos": 10,
    "forca": 16,
    "destreza": 18,
    "magia": 17,
    "velocidade": 18,
    "inteligencia": 20,
    "resistencia": "velocidade"
  },
  {
    "id": 3,
    "nome": "Tanis Half-Elven",
    "raridade": "lendaria",
    "pontos": 10,
    "forca": 17,
    "destreza": 17,
    "magia": 20,
    "velocidade": 16,
    "inteligencia": 18,
    "resistencia": "velocidade"
  },
  {
    "id": 4,
    "nome": "Raistlin Majere",
    "raridade": "lendaria",
    "pontos": 10,
    "forca": 19,
    "destreza": 17,
    "magia": 16,
    "velocidade": 19,
    "inteligencia": 19,
    "resistencia": "destreza"
  },
  {
    "id": 5,
    "nome": "Fizban",
    "raridade": "lendaria",
    "pontos": 10,
    "forca": 17,
    "destreza": 19,
    "magia": 18,
    "velocidade": 19,
    "inteligencia": 19,
    "resistencia": "magia"
  },
  {
    "id": 6,
    "nome": "Minsc & Boo",
    "raridade": "epica",
    "pontos": 5,
    "forca": 15,
    "destreza": 14,
    "magia": 15,
    "velocidade": 15,
    "inteligencia": 16,
    "resistencia": "forca"
  },
  {
    "id": 7,
    "nome": "Jaheira Druid",
    "raridade": "epica",
    "pontos": 5,
    "forca": 17,
    "destreza": 15,
    "magia": 13,
    "velocidade": 17,
    "inteligencia": 16,
    "resistencia": "forca"
  },
  {
    "id": 8,
    "nome": "Keldorn Paladin",
    "raridade": "epica",
    "pontos": 5,
    "forca": 17,
    "destreza": 14,
    "magia": 16,
    "velocidade": 14,
    "inteligencia": 16,
    "resistencia": "velocidade"
  },
  {
    "id": 9,
    "nome": "Edwin Sorcerer",
    "raridade": "epica",
    "pontos": 5,
    "forca": 16,
    "destreza": 17,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 10,
    "nome": "Imoen Thief",
    "raridade": "epica",
    "pontos": 5,
    "forca": 14,
    "destreza": 15,
    "magia": 16,
    "velocidade": 15,
    "inteligencia": 17,
    "resistencia": "inteligencia"
  },
  {
    "id": 11,
    "nome": "Caramon Majere",
    "raridade": "epica",
    "pontos": 5,
    "forca": 14,
    "destreza": 14,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 16,
    "resistencia": "inteligencia"
  },
  {
    "id": 12,
    "nome": "Sturm Brightblade",
    "raridade": "epica",
    "pontos": 5,
    "forca": 13,
    "destreza": 15,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 13,
    "nome": "Gilthanas",
    "raridade": "epica",
    "pontos": 5,
    "forca": 16,
    "destreza": 14,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 16,
    "resistencia": "inteligencia"
  },
  {
    "id": 14,
    "nome": "Riverwind",
    "raridade": "epica",
    "pontos": 5,
    "forca": 15,
    "destreza": 17,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 15,
    "resistencia": "magia"
  },
  {
    "id": 15,
    "nome": "Goldmoon",
    "raridade": "epica",
    "pontos": 5,
    "forca": 15,
    "destreza": 17,
    "magia": 13,
    "velocidade": 15,
    "inteligencia": 15,
    "resistencia": "forca"
  },
  {
    "id": 16,
    "nome": "Cadderly Priest",
    "raridade": "epica",
    "pontos": 5,
    "forca": 13,
    "destreza": 15,
    "magia": 15,
    "velocidade": 17,
    "inteligencia": 17,
    "resistencia": "magia"
  },
  {
    "id": 17,
    "nome": "Danica Monk",
    "raridade": "epica",
    "pontos": 5,
    "forca": 17,
    "destreza": 14,
    "magia": 17,
    "velocidade": 17,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 18,
    "nome": "Ivan Dwarf",
    "raridade": "epica",
    "pontos": 5,
    "forca": 16,
    "destreza": 13,
    "magia": 17,
    "velocidade": 16,
    "inteligencia": 15,
    "resistencia": "magia"
  },
  {
    "id": 19,
    "nome": "Korgan Berserker",
    "raridade": "epica",
    "pontos": 5,
    "forca": 13,
    "destreza": 16,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 17,
    "resistencia": "destreza"
  },
  {
    "id": 20,
    "nome": "Sarevok Warlord",
    "raridade": "epica",
    "pontos": 5,
    "forca": 13,
    "destreza": 16,
    "magia": 16,
    "velocidade": 15,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 21,
    "nome": "Cleric of Lathander",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 10,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "inteligencia"
  },
  {
    "id": 22,
    "nome": "Knight of Torm",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 11,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 23,
    "nome": "Priestess of Helm",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 10,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 24,
    "nome": "Ranger Scout",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 12,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 25,
    "nome": "Rogue Assassin",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 11,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 14,
    "resistencia": "velocidade"
  },
  {
    "id": 26,
    "nome": "Fighter Champion",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 11,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 27,
    "nome": "Barbarian Berserker",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 11,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 28,
    "nome": "Monk Master",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 14,
    "resistencia": "velocidade"
  },
  {
    "id": 29,
    "nome": "Paladin Crusader",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 30,
    "nome": "Sorcerer Noble",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 10,
    "magia": 13,
    "velocidade": 12,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 31,
    "nome": "Wizard Enchanter",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 13,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 32,
    "nome": "Druid Shapeshifter",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 13,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "destreza"
  },
  {
    "id": 33,
    "nome": "Bard Performer",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 13,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "velocidade"
  },
  {
    "id": 34,
    "nome": "Warlock Pact",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 35,
    "nome": "Artificer Smith",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 13,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 36,
    "nome": "Elf Archer",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 14,
    "velocidade": 11,
    "inteligencia": 14,
    "resistencia": "inteligencia"
  },
  {
    "id": 37,
    "nome": "Human Swordsman",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 38,
    "nome": "Dwarf Miner",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 39,
    "nome": "Halfling Thief",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 13,
    "magia": 13,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 40,
    "nome": "Gnome Tinkerer",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "velocidade"
  },
  {
    "id": 41,
    "nome": "Tiefling Warlock",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 12,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 42,
    "nome": "Dragonborn Knight",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 43,
    "nome": "Half-Orc Warrior",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 12,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 44,
    "nome": "Half-Elf Ranger",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 12,
    "inteligencia": 13,
    "resistencia": "destreza"
  },
  {
    "id": 45,
    "nome": "Half-Giant Fighter",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 14,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 46,
    "nome": "Orc Shaman",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 10,
    "magia": 13,
    "velocidade": 12,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 47,
    "nome": "Goblin King",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 10,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 48,
    "nome": "Bugbear Warrior",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 14,
    "magia": 14,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 49,
    "nome": "Gnoll Hunter",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 11,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 50,
    "nome": "Hobgoblin Commander",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 12,
    "velocidade": 12,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 51,
    "nome": "Minotaur Champion",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 12,
    "magia": 13,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 52,
    "nome": "Centaur Ranger",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 53,
    "nome": "Satyr Mage",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 11,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 54,
    "nome": "Faun Guardian",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 10,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 55,
    "nome": "Dryad Enchantress",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 56,
    "nome": "Nymph Siren",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 12,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 13,
    "resistencia": "velocidade"
  },
  {
    "id": 57,
    "nome": "Pixie Mage",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 58,
    "nome": "Sprite Rogue",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 14,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 59,
    "nome": "Fey Knight",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 12,
    "magia": 11,
    "velocidade": 12,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 60,
    "nome": "Shadow Elf",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 61,
    "nome": "Drow Priestess",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 11,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "forca"
  },
  {
    "id": 62,
    "nome": "Drow Paladin",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 63,
    "nome": "Yuan-ti Abomination",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 13,
    "resistencia": "inteligencia"
  },
  {
    "id": 64,
    "nome": "Duergar Champion",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 13,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 65,
    "nome": "Svirfneblin Rogue",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 13,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 12,
    "resistencia": "forca"
  },
  {
    "id": 66,
    "nome": "Tortle Monk",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 11,
    "velocidade": 14,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 67,
    "nome": "Aarakocra Ranger",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 13,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 68,
    "nome": "Firbolg Druid",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 12,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "destreza"
  },
  {
    "id": 69,
    "nome": "Tabaxi Bard",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 10,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 70,
    "nome": "Genasi Wizard",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 14,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 71,
    "nome": "Lizardfolk Fighter",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 10,
    "magia": 11,
    "velocidade": 12,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 72,
    "nome": "Kenku Rogue",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 12,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 73,
    "nome": "Kobold Sorcerer",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 12,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 74,
    "nome": "Cloud Giant Scholar",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 11,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 75,
    "nome": "Hill Giant Leader",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 14,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 76,
    "nome": "Cleric of Lathander #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 14,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 77,
    "nome": "Knight of Torm #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 11,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 78,
    "nome": "Priestess of Helm #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 13,
    "magia": 13,
    "velocidade": 12,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 79,
    "nome": "Ranger Scout #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 13,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 80,
    "nome": "Rogue Assassin #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 14,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 81,
    "nome": "Fighter Champion #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 14,
    "magia": 13,
    "velocidade": 13,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 82,
    "nome": "Barbarian Berserker #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 14,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 83,
    "nome": "Monk Master #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 10,
    "magia": 14,
    "velocidade": 13,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 84,
    "nome": "Paladin Crusader #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 85,
    "nome": "Sorcerer Noble #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 14,
    "magia": 11,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "inteligencia"
  },
  {
    "id": 86,
    "nome": "Wizard Enchanter #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 11,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 87,
    "nome": "Druid Shapeshifter #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 12,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 88,
    "nome": "Bard Performer #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 89,
    "nome": "Warlock Pact #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 10,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 90,
    "nome": "Artificer Smith #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 10,
    "velocidade": 12,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 91,
    "nome": "Elf Archer #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 10,
    "magia": 12,
    "velocidade": 12,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 92,
    "nome": "Human Swordsman #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 10,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 93,
    "nome": "Dwarf Miner #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 10,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "forca"
  },
  {
    "id": 94,
    "nome": "Halfling Thief #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 12,
    "resistencia": "inteligencia"
  },
  {
    "id": 95,
    "nome": "Gnome Tinkerer #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 12,
    "resistencia": "inteligencia"
  },
  {
    "id": 96,
    "nome": "Tiefling Warlock #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 97,
    "nome": "Dragonborn Knight #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 14,
    "resistencia": "forca"
  },
  {
    "id": 98,
    "nome": "Half-Orc Warrior #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 14,
    "magia": 14,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 99,
    "nome": "Half-Elf Ranger #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 100,
    "nome": "Half-Giant Fighter #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 12,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 101,
    "nome": "Orc Shaman #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 13,
    "magia": 13,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 102,
    "nome": "Goblin King #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 13,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 14,
    "resistencia": "forca"
  },
  {
    "id": 103,
    "nome": "Bugbear Warrior #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 104,
    "nome": "Gnoll Hunter #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 11,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "forca"
  },
  {
    "id": 105,
    "nome": "Hobgoblin Commander #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 12,
    "magia": 14,
    "velocidade": 13,
    "inteligencia": 11,
    "resistencia": "forca"
  },
  {
    "id": 106,
    "nome": "Minotaur Champion #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 10,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 14,
    "resistencia": "inteligencia"
  },
  {
    "id": 107,
    "nome": "Centaur Ranger #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 13,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 13,
    "resistencia": "velocidade"
  },
  {
    "id": 108,
    "nome": "Satyr Mage #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 14,
    "magia": 14,
    "velocidade": 12,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 109,
    "nome": "Faun Guardian #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 11,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 12,
    "resistencia": "destreza"
  },
  {
    "id": 110,
    "nome": "Dryad Enchantress #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 12,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "destreza"
  },
  {
    "id": 111,
    "nome": "Nymph Siren #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 14,
    "magia": 14,
    "velocidade": 11,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 112,
    "nome": "Pixie Mage #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 12,
    "magia": 10,
    "velocidade": 13,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 113,
    "nome": "Sprite Rogue #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 12,
    "magia": 13,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "forca"
  },
  {
    "id": 114,
    "nome": "Fey Knight #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 14,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 115,
    "nome": "Shadow Elf #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 12,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 116,
    "nome": "Drow Priestess #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 14,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 117,
    "nome": "Drow Paladin #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 10,
    "magia": 14,
    "velocidade": 12,
    "inteligencia": 12,
    "resistencia": "velocidade"
  },
  {
    "id": 118,
    "nome": "Yuan-ti Abomination #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 13,
    "magia": 13,
    "velocidade": 11,
    "inteligencia": 14,
    "resistencia": "velocidade"
  },
  {
    "id": 119,
    "nome": "Duergar Champion #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 10,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 13,
    "resistencia": "inteligencia"
  },
  {
    "id": 120,
    "nome": "Svirfneblin Rogue #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 12,
    "destreza": 10,
    "magia": 10,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 121,
    "nome": "Tortle Monk #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 12,
    "inteligencia": 13,
    "resistencia": "destreza"
  },
  {
    "id": 122,
    "nome": "Aarakocra Ranger #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 10,
    "magia": 12,
    "velocidade": 11,
    "inteligencia": 13,
    "resistencia": "velocidade"
  },
  {
    "id": 123,
    "nome": "Firbolg Druid #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 12,
    "resistencia": "magia"
  },
  {
    "id": 124,
    "nome": "Tabaxi Bard #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 14,
    "destreza": 12,
    "magia": 12,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "magia"
  },
  {
    "id": 125,
    "nome": "Genasi Wizard #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 12,
    "velocidade": 14,
    "inteligencia": 14,
    "resistencia": "inteligencia"
  },
  {
    "id": 126,
    "nome": "Lizardfolk Fighter #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 12,
    "magia": 14,
    "velocidade": 14,
    "inteligencia": 12,
    "resistencia": "forca"
  },
  {
    "id": 127,
    "nome": "Kenku Rogue #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 128,
    "nome": "Kobold Sorcerer #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 13,
    "destreza": 12,
    "magia": 12,
    "velocidade": 10,
    "inteligencia": 14,
    "resistencia": "magia"
  },
  {
    "id": 129,
    "nome": "Cloud Giant Scholar #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 11,
    "destreza": 10,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 13,
    "resistencia": "forca"
  },
  {
    "id": 130,
    "nome": "Hill Giant Leader #1",
    "raridade": "rara",
    "pontos": 3,
    "forca": 10,
    "destreza": 11,
    "magia": 11,
    "velocidade": 13,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 131,
    "nome": "Village Guard",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 8,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 132,
    "nome": "Town Watchman",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 133,
    "nome": "Bandit Thug",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 7,
    "resistencia": "destreza"
  },
  {
    "id": 134,
    "nome": "Brigand Scout",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 135,
    "nome": "Outlaw Rogue",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 9,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 136,
    "nome": "Adventurer Novice",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 137,
    "nome": "Sellsword Mercenary",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 8,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 138,
    "nome": "Brigand Leader",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 139,
    "nome": "Highwayman",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 8,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "forca"
  },
  {
    "id": 140,
    "nome": "Cutthroat",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 7,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 141,
    "nome": "Poacher Scout",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 7,
    "resistencia": "destreza"
  },
  {
    "id": 142,
    "nome": "Ruffian Bully",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 143,
    "nome": "Cultist Fanatic",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 8,
    "magia": 11,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "forca"
  },
  {
    "id": 144,
    "nome": "Acolyte Novice",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 11,
    "magia": 9,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 145,
    "nome": "Hedge Wizard",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 146,
    "nome": "Apprentice Mage",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 147,
    "nome": "Novice Priest",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 148,
    "nome": "Witch Crone",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 11,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 149,
    "nome": "Tavern Brawler",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 150,
    "nome": "Street Thug",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 151,
    "nome": "Militia Soldier",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 152,
    "nome": "Palace Guard",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 9,
    "velocidade": 7,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 153,
    "nome": "Caravan Guard",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 154,
    "nome": "Dungeon Guard",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 155,
    "nome": "Knight Squire",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 156,
    "nome": "Priestess Initiate",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 157,
    "nome": "Wizard Apprentice",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 158,
    "nome": "Rogue Trainee",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 9,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 159,
    "nome": "Monk Novice",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 160,
    "nome": "Barbarian Recruit",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 161,
    "nome": "Village Guard #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 11,
    "magia": 9,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 162,
    "nome": "Town Watchman #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 163,
    "nome": "Bandit Thug #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 164,
    "nome": "Brigand Scout #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 8,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 165,
    "nome": "Outlaw Rogue #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 9,
    "velocidade": 7,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 166,
    "nome": "Adventurer Novice #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 167,
    "nome": "Sellsword Mercenary #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 168,
    "nome": "Brigand Leader #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 8,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 169,
    "nome": "Highwayman #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 10,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 170,
    "nome": "Cutthroat #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 11,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 171,
    "nome": "Poacher Scout #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 172,
    "nome": "Ruffian Bully #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 7,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "destreza"
  },
  {
    "id": 173,
    "nome": "Cultist Fanatic #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 174,
    "nome": "Acolyte Novice #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 175,
    "nome": "Hedge Wizard #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 176,
    "nome": "Apprentice Mage #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 8,
    "resistencia": "destreza"
  },
  {
    "id": 177,
    "nome": "Novice Priest #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 178,
    "nome": "Witch Crone #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 179,
    "nome": "Tavern Brawler #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 180,
    "nome": "Street Thug #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 181,
    "nome": "Militia Soldier #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 182,
    "nome": "Palace Guard #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 183,
    "nome": "Caravan Guard #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 7,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 184,
    "nome": "Dungeon Guard #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 11,
    "velocidade": 9,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 185,
    "nome": "Knight Squire #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 186,
    "nome": "Priestess Initiate #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "forca"
  },
  {
    "id": 187,
    "nome": "Wizard Apprentice #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 188,
    "nome": "Rogue Trainee #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 189,
    "nome": "Monk Novice #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 190,
    "nome": "Barbarian Recruit #1",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 11,
    "velocidade": 9,
    "inteligencia": 9,
    "resistencia": "forca"
  },
  {
    "id": 191,
    "nome": "Village Guard #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 192,
    "nome": "Town Watchman #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 193,
    "nome": "Bandit Thug #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 194,
    "nome": "Brigand Scout #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 195,
    "nome": "Outlaw Rogue #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 196,
    "nome": "Adventurer Novice #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 197,
    "nome": "Sellsword Mercenary #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 9,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 198,
    "nome": "Brigand Leader #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 199,
    "nome": "Highwayman #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 11,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 200,
    "nome": "Cutthroat #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 9,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 201,
    "nome": "Poacher Scout #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 202,
    "nome": "Ruffian Bully #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 203,
    "nome": "Cultist Fanatic #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 8,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 204,
    "nome": "Acolyte Novice #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 8,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "forca"
  },
  {
    "id": 205,
    "nome": "Hedge Wizard #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 206,
    "nome": "Apprentice Mage #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 8,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 207,
    "nome": "Novice Priest #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 208,
    "nome": "Witch Crone #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 9,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 209,
    "nome": "Tavern Brawler #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 210,
    "nome": "Street Thug #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 211,
    "nome": "Militia Soldier #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "destreza"
  },
  {
    "id": 212,
    "nome": "Palace Guard #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 213,
    "nome": "Caravan Guard #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 214,
    "nome": "Dungeon Guard #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 9,
    "magia": 11,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 215,
    "nome": "Knight Squire #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 216,
    "nome": "Priestess Initiate #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 9,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 217,
    "nome": "Wizard Apprentice #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 218,
    "nome": "Rogue Trainee #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "destreza"
  },
  {
    "id": 219,
    "nome": "Monk Novice #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "destreza"
  },
  {
    "id": 220,
    "nome": "Barbarian Recruit #2",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 221,
    "nome": "Village Guard #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 222,
    "nome": "Town Watchman #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 7,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "velocidade"
  },
  {
    "id": 223,
    "nome": "Bandit Thug #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 8,
    "resistencia": "magia"
  },
  {
    "id": 224,
    "nome": "Brigand Scout #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 225,
    "nome": "Outlaw Rogue #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 226,
    "nome": "Adventurer Novice #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 8,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "forca"
  },
  {
    "id": 227,
    "nome": "Sellsword Mercenary #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 7,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 228,
    "nome": "Brigand Leader #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 229,
    "nome": "Highwayman #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 230,
    "nome": "Cutthroat #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 7,
    "resistencia": "forca"
  },
  {
    "id": 231,
    "nome": "Poacher Scout #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 232,
    "nome": "Ruffian Bully #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 11,
    "resistencia": "forca"
  },
  {
    "id": 233,
    "nome": "Cultist Fanatic #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 11,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 234,
    "nome": "Acolyte Novice #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 235,
    "nome": "Hedge Wizard #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 8,
    "magia": 11,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 236,
    "nome": "Apprentice Mage #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "destreza"
  },
  {
    "id": 237,
    "nome": "Novice Priest #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 238,
    "nome": "Witch Crone #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 8,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 239,
    "nome": "Tavern Brawler #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 7,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 240,
    "nome": "Street Thug #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 8,
    "velocidade": 9,
    "inteligencia": 8,
    "resistencia": "magia"
  },
  {
    "id": 241,
    "nome": "Militia Soldier #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 7,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 242,
    "nome": "Palace Guard #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 243,
    "nome": "Caravan Guard #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 244,
    "nome": "Dungeon Guard #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 245,
    "nome": "Knight Squire #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 11,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 246,
    "nome": "Priestess Initiate #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 247,
    "nome": "Wizard Apprentice #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 248,
    "nome": "Rogue Trainee #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 249,
    "nome": "Monk Novice #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 250,
    "nome": "Barbarian Recruit #3",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 9,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 251,
    "nome": "Village Guard #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 252,
    "nome": "Town Watchman #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 253,
    "nome": "Bandit Thug #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 9,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 254,
    "nome": "Brigand Scout #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 9,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 255,
    "nome": "Outlaw Rogue #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 9,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 256,
    "nome": "Adventurer Novice #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 257,
    "nome": "Sellsword Mercenary #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "destreza"
  },
  {
    "id": 258,
    "nome": "Brigand Leader #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 259,
    "nome": "Highwayman #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 260,
    "nome": "Cutthroat #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 261,
    "nome": "Poacher Scout #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 7,
    "magia": 9,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 262,
    "nome": "Ruffian Bully #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 7,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 11,
    "resistencia": "magia"
  },
  {
    "id": 263,
    "nome": "Cultist Fanatic #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 8,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "inteligencia"
  },
  {
    "id": 264,
    "nome": "Acolyte Novice #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 265,
    "nome": "Hedge Wizard #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "velocidade"
  },
  {
    "id": 266,
    "nome": "Apprentice Mage #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 10,
    "velocidade": 9,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 267,
    "nome": "Novice Priest #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 7,
    "velocidade": 10,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 268,
    "nome": "Witch Crone #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 9,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 269,
    "nome": "Tavern Brawler #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 10,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "forca"
  },
  {
    "id": 270,
    "nome": "Street Thug #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 8,
    "velocidade": 9,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 271,
    "nome": "Militia Soldier #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 7,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 272,
    "nome": "Palace Guard #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 7,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 273,
    "nome": "Caravan Guard #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 8,
    "resistencia": "inteligencia"
  },
  {
    "id": 274,
    "nome": "Dungeon Guard #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 8,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "inteligencia"
  },
  {
    "id": 275,
    "nome": "Knight Squire #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "magia"
  },
  {
    "id": 276,
    "nome": "Priestess Initiate #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 10,
    "magia": 9,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "magia"
  },
  {
    "id": 277,
    "nome": "Wizard Apprentice #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 278,
    "nome": "Rogue Trainee #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 10,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 11,
    "resistencia": "forca"
  },
  {
    "id": 279,
    "nome": "Monk Novice #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 8,
    "magia": 9,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "forca"
  },
  {
    "id": 280,
    "nome": "Barbarian Recruit #4",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 9,
    "velocidade": 8,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 281,
    "nome": "Village Guard #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 7,
    "velocidade": 9,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 282,
    "nome": "Town Watchman #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 9,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 9,
    "resistencia": "destreza"
  },
  {
    "id": 283,
    "nome": "Bandit Thug #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 7,
    "magia": 9,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 284,
    "nome": "Brigand Scout #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "destreza"
  },
  {
    "id": 285,
    "nome": "Outlaw Rogue #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 7,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 286,
    "nome": "Adventurer Novice #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 9,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 287,
    "nome": "Sellsword Mercenary #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 11,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 288,
    "nome": "Brigand Leader #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 9,
    "destreza": 10,
    "magia": 10,
    "velocidade": 10,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 289,
    "nome": "Highwayman #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 8,
    "velocidade": 7,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 290,
    "nome": "Cutthroat #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 7,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "inteligencia"
  },
  {
    "id": 291,
    "nome": "Poacher Scout #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 11,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 292,
    "nome": "Ruffian Bully #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 10,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 9,
    "resistencia": "velocidade"
  },
  {
    "id": 293,
    "nome": "Cultist Fanatic #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "forca"
  },
  {
    "id": 294,
    "nome": "Acolyte Novice #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 8,
    "magia": 9,
    "velocidade": 11,
    "inteligencia": 7,
    "resistencia": "magia"
  },
  {
    "id": 295,
    "nome": "Hedge Wizard #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 11,
    "magia": 8,
    "velocidade": 11,
    "inteligencia": 11,
    "resistencia": "velocidade"
  },
  {
    "id": 296,
    "nome": "Apprentice Mage #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 7,
    "magia": 10,
    "velocidade": 8,
    "inteligencia": 7,
    "resistencia": "inteligencia"
  },
  {
    "id": 297,
    "nome": "Novice Priest #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 10,
    "destreza": 10,
    "magia": 11,
    "velocidade": 7,
    "inteligencia": 9,
    "resistencia": "magia"
  },
  {
    "id": 298,
    "nome": "Witch Crone #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 11,
    "destreza": 11,
    "magia": 11,
    "velocidade": 10,
    "inteligencia": 7,
    "resistencia": "velocidade"
  },
  {
    "id": 299,
    "nome": "Tavern Brawler #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 7,
    "destreza": 11,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 8,
    "resistencia": "magia"
  },
  {
    "id": 300,
    "nome": "Street Thug #5",
    "raridade": "comum",
    "pontos": 1,
    "forca": 8,
    "destreza": 8,
    "magia": 10,
    "velocidade": 11,
    "inteligencia": 10,
    "resistencia": "forca"
  }
];